# name of workflow that will be displayed on the actions page
name: Create example VCF files

# execute workflow only when these files are modified
on:
  push:
    paths:
      - 'workflow/**'
      - '.github/workflows/variant_call.yml'
  workflow_dispatch:

# a list of the jobs that run as part of the workflow
jobs:
  variant_call:
    runs-on: ubuntu-latest

    # a list of the steps that will run as part of the job
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."

      - name: Install tools
        run: cd workflow && ./install.sh

      - name: Run workflow
        run: cd workflow/simple && make

      - name: Copy results
        run: |
          cp workflow/simple/*.vcf.gz eg
          cp workflow/simple/*[0-9].fa eg

      - name: Commit report
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'davetingpongtang@gmail.com'
          git add eg/aln*.vcf.gz eg/*[0-9].fa
          git commit -m "Workflow files"
          git push origin master

      - run: echo "This job's status is ${{ job.status }}."

